### PR TITLE
cmake: support ninja as the generator

### PR DESCRIPTION
**Pull request by senior7515**
/cc @noahdesu

### CODE REVIEW

**Comment by noahdesu** [comment]
the problem with this patch is ninja seems to default to parallel builds, but we have to add it in directly for make-based builds. i mostly don't care about make vs ninja, just something to think about.

**Comment by noahdesu** [comment]
oh! nix that. this actually probably does work, I was thinking you replaced `make_command` with CMAKE_MAKE_PROGRAM. lgtm if it works.

**Comment by noahdesu** [comment]
wait. i take that back. i'm not really sure what you are trying to do there. ninja was already working.

**Comment by senior7515** [comment]
@noahdesu  i think you might be confused. 

This branch: 

1. keeps make parallelism via the -j $build... 
2. enables ninja & cmake to work

I tested this. am I missing something?

**Comment by noahdesu** [comment]
The change below from this PR causes `cmake` to be run in the build directory, which I don't think really does anything, since ${CMAKE_COMMAND} isn't the default, it's just the `cmake` binary.

```diff
@@ -348,7 +349,7 @@ ExternalProject_Add(xxhash
     -DBUILD_SHARED_LIBS=OFF
     -DBUILD_ENABLE_INLINE_API=ON
     <SOURCE_DIR>/cmake_unofficial
-  BUILD_COMMAND ${make_command})
+  BUILD_COMMAND ${CMAKE_COMMAND})
```

This can be seen from the output below where cmake is run in the build directory and you get the usage warning printed (`cmake [options] <path-to-source>`).

```
-- Build files have been written to: /home/nwatkins/src/smf/build/smf-deps-build/xxhash-prefix/src/xxhash-build
[ 75%] Performing build step for 'xxhash'
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

[ 87%] Performing install step for 'xxhash'
```

The build then is probably happening in the install step, via `make install` (in my case since I'm using unix makefile generator).

```
[ 87%] Performing install step for 'xxhash'
Scanning dependencies of target xxhash
[ 25%] Building C object CMakeFiles/xxhash.dir/home/nwatkins/src/smf/build/smf-deps-build/xxhash-prefix/src/xxhash/xxhash.c.o
[ 50%] Linking C static library libxxhash.a
```

> * keeps make parallelism via the -j $build...

How so? When ninja is used a default level of build parallelism is used, but make requires `-j` and I don't see any evidence of cmake adding this automatically. Here it is straced without `-j`.

`execve("/usr/bin/gmake", ["/usr/bin/gmake", "-f", "CMakeFiles/Makefile2", "all"], 0x55d420a13c40 /* 100 vars */ <unfinished ...>`

Before this change my observation was that `set(make_command ${CMAKE_MAKE_PROGRAM} -j ${build_concurrency_factor})` worked correctly for make and ninja producing `make -j` or `ninja -j`.

> * enables ninja & cmake to work

How did it fail? Ninja was already working on at least one distribution: https://travis-ci.org/smfrpc/smf/jobs/498065719

**Pull request merged**
